plugins {
    id "com.android.application"
}

android {
    namespace "com.justdance.remote"
    compileSdk 35

    defaultConfig {
        applicationId "com.justdance.remote"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "0.2.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

